server:
  port: 8011

spring:

  application:
    name: zuul
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: bitlyuf
    
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
      
app:
  registration:
    url: /users-api/users
      
  login:
    url: /users-api/users/authentication
    
  actuator:
    zuul:
      url: /actuator/**
      
    users-api:
      url: /users-api/actuator/**

  jwt:
    secret: m@rio
    
  authorization:
      name: Authorization
      prefix: Bearer