server:
  port: ${PORT:0}
  
spring:
  application:
    name: users-api
      
  devtools:
      restart:
        enabled: true
        
  sleuth:
    sampler:
      probability: 1
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true

logging:
  file:
    name: ${spring.application.name}.log
  level:
    br.com.photoapp.ui.client: off
    
   