server:
  port: 8012

spring:
  application:
    name: PhotoAppConfigServer
    
  profiles:
    active: git
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MarioJunio/PhotoAppConfiguration.git
          username: MarioJunio
          password: "{cipher}AQB02yrXkYmqQle7TC2aElX3XEoUltsb2JJtywcXl31hQffy6GQWawo1Ihx9akL36QgNhYAeUvWtqtwkhye5gwSQ676afbfo/c9Wc9IUds0yZv/jPMkLUg66le/Q4N3ezV16nW7Csm2RjhSa1SZQcWemeiQIG22xfXoR+BS+ZMW/fz9e9xadDsyEZG3UMHwu8NtHnBvzSvaPuKRhTNgGoA4jJ8i4+TXyNN8AykIizs02wXExw+d3s+DGmQcLFe3njiJVakiNMyepFfYRiDC59AdVzPqg4mewRD4rI8VMfw6Ktf2LmIdgQRu2UONpujdDWQMlVYjD8Qc2d8birDWBO2sTo1qnDye1mMDjFCRHOV8WGB2Umvp4Vo22wzjM+hhgNt8="
          clone-on-start: true
      
        native:
          search-locations: file:///Users/mariomartins/mj-workspace/PhotoAppConfigurationls
          
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
        